source 'http://rubygems.org'

gem 'sinatra'
gem 'mongo'
gem 'bson_ext'
gem 'thin'
gem 'haml'
gem 'websocket-native'
gem 'faye'
gem 'faye-websocket'
gem 'pusher'
gem 'pusher-client'
gem 'pubnub'
gem 'pry'
gem 'rufus-scheduler'
gem 'chronic'
gem 'newrelic_rpm'